
networks: 
  smart_invite_net:
    driver: bridge

services:
  dev-db:
    image: mysql:8.1
    container_name: res-smart_invite_dev
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQLROOTPASSWORD}
        MYSQL_DATABASE: ${MYSQLDATABASE}
        MYSQL_USER: ${MYSQLUSER}
        MYSQL_PASSWORD: ${MYSQLPASSWORD}
    ports:
      - "3308:3306"
    networks:
      - smart_invite_net
    volumes:
      - dev_db_data:/var/lib/mysql

  prod-db:
    image: mysql:8.1
    container_name: res-smart_invite_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLROOTPASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
    ports:
      - "3309:3306"
    networks:
      - smart_invite_net
    volumes:
      - prod_db_data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer_smart_invite
    restart: always
    ports:
      - "8084:8080"
    environment:
      ADMINER_DEFAULT_SERVER: dev-db
    networks:
      - smart_invite_net
    depends_on:
      - dev-db


volumes:
  dev_db_data:
  prod_db_data:
